#!/usr/bin/env python
"""
Parse out an F1 score from a mafComparator XML file.
"""
from bs4 import BeautifulSoup
from argparse import ArgumentParser

def get_f1(soup):
    precision = float(soup.alignmentcomparisons.find_all("homologytests")[0].aggregateresults.all.get('average'))
    recall = float(soup.alignmentcomparisons.find_all("homologytests")[1].aggregateresults.all.get('average'))
    return 2 * (precision * recall) / (precision + recall)

def parse_args():
    parser = ArgumentParser(description=__doc__)
    parser.add_argument('xml', help='mafComparator XML output file')
    return parser.parse_args()

def main():
    opts = parse_args()
    with open(opts.xml) as f:
        soup = BeautifulSoup(f, 'html.parser')
        print get_f1(soup)

if __name__ == '__main__':
    main()
