- name: Create EC2 instance(s)
  hosts: localhost
  remote_user: ubuntu
  gather_facts: False
  vars:
    keypair: jcarmstr@ucsc.edu
    instance_type: c5.9xlarge
    instance_name: 200m-perspectives
    spot_price: 0.8
    security_group: launch-wizard-16
    subnet: subnet-9b98e0d2
    image: 	ami-0135f076a31aebe66
    region: us-west-2
    num_workers: 10
    data_snapshot_id: snap-0d5b332f34c333249

  tasks:
    - name: Launch node instance(s)
      ec2:
         spot_price: "{{ spot_price }}"
         spot_wait_timeout: 300
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         instance_tags:
           Owner: "{{ keypair }}"
           Name: "{{ instance_name }}"
         volumes:
         - device_name: /dev/sda1
           volume_type: gp2
           volume_size: 300
           delete_on_termination: yes
         count: "{{ num_workers }}"
         vpc_subnet_id: "{{ subnet }}"
         assign_public_ip: yes
      register: ec2

    - name: Attach volume from snapshot
      ec2_vol:
        instance: "{{ item.id }}"
        region: "{{ region }}"
        snapshot: "{{ data_snapshot_id }}"
        delete_on_termination: yes
        volume_type: "gp2"
      with_items: "{{ ec2.instances }}"

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groups:
          - launched
        ansible_user: ubuntu
        host_key_checking: false
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        state: started
        delay: 10
        timeout: 320
      with_items: "{{ ec2.instances }}"

- name: Add python so ansible stops whining
  hosts: launched
  gather_facts: false
  tasks:
    - name: Configure apt
      raw: "sudo apt update && sudo apt install -y python"

- name: Mount attached data volume
  hosts: launched
  become: true
  tasks:
    - mount:
        path: /mnt2
        src: /dev/nvme1n1
        state: mounted
        fstype: ext4
    - shell: "chown ubuntu /mnt2"
    - apt:
        name: fio
    - shell: "chown ubuntu /mnt2/tmp"
    - shell: "nohup fio --filename=/dev/nvme1n1 --rw=read --bs=128k --iodepth=32 --ioengine=libaio --direct=1 --name=volume-initialize </dev/null >/dev/null 2>&1 &"
      async: 10
      poll: 0

- name: Build parasol
  hosts: launched
  vars:
    packages:
      - build-essential
      - libz-dev
      - libpng-dev
      - libssl-dev
      - uuid-dev
      - git
    para_hub_ip: '172.31.34.137'
  tasks:
    - name: Add apt dependencies
      become: true
      apt:
        name: "{{ packages }}"
    - name: Add paraNode patch
      copy:
        src: paraNode_memory.patch
        dest: "~/paraNode_memory.patch"
    - name: Build kent tools
      shell: |
        set -o errexit
        git clone https://github.com/ucscgenomebrowser/kent.git
        mkdir ~/bin
        cd kent
        git apply < ~/paraNode_memory.patch
        cd src/lib
        MACHTYPE=x86-64 make -j 8
        cd ../htslib
        MACHTYPE=x86-64 make -j 8
        cd ../parasol
        MACHTYPE=x86-64 make -j 8 userApps
        sudo cp ~/bin/x86-64/para* /usr/bin/
    - name: Copy systemd unit file
      become: true
      copy:
        content: |
          [Unit]
          After=network.target
          [Service]
          Type=simple
          ExecStart=/usr/bin/paraNode start -debug -hub={{ para_hub_ip }} -cpu=36
          [Install]
          WantedBy=multi-user.target
        dest: '/etc/systemd/system/paraNode.service'
    - name: Start paraNode
      become: true
      systemd:
        daemon_reload: yes
        state: started
        name: paraNode

- name: Build hal
  hosts: launched
  tasks:
    - name: Install HDF5
      become: true
      vars:
        packages:
          - libhdf5-cpp-11
          - libhdf5-dev
      apt:
        name: "{{ packages }}"
    - name: Build hal tools
      shell: |
        set -o errexit
        git clone https://github.com/comparativegenomicstoolkit/sonLib.git
        cd sonLib
        make
        cd ..
        git clone https://github.com/comparativegenomicstoolkit/hal.git
        cd hal
        git checkout 6854856bcb94efa059330359ffc987b3f944aa6a
        sed -i 's/(_header->dirty)/(0)/g' api/mmap_impl/mmapFile.cpp
        make -j 32
        sudo cp bin/* /usr/bin/

- name: Mount EFS
  hosts: launched
  vars:
    efs_id: fs-a95a0a01
  tasks:
    - name: Build EFS helper
      shell: |
        set -o errexit
        git clone https://github.com/aws/efs-utils
        cd efs-utils
        ./build-deb.sh
        sudo apt-get -y install ./build/amazon-efs-utils*deb
    - name: Mount EFS on /efs
      become: true
      shell: "mkdir /efs && mount -t efs {{ efs_id }}:/ /efs && sudo chown ubuntu /efs"

- name: Copy needed binaries
  hosts: launched
  become: true
  tasks:
    - apt:
        name: zstd
